//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TimeConfig.proto
namespace m
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeConfig")]
  public partial class TimeConfig : global::ProtoBuf.IExtensible
  {
    public TimeConfig() {}
    
    private int _StageID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"StageID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StageID
    {
      get { return _StageID; }
      set { _StageID = value; }
    }
    private float _ClickCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ClickCount", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ClickCount
    {
      get { return _ClickCount; }
      set { _ClickCount = value; }
    }
    private float _AddNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AddNum", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float AddNum
    {
      get { return _AddNum; }
      set { _AddNum = value; }
    }
    private float _MinusNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MinusNum", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float MinusNum
    {
      get { return _MinusNum; }
      set { _MinusNum = value; }
    }
    private float _dampTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dampTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float dampTime
    {
      get { return _dampTime; }
      set { _dampTime = value; }
    }
    private string _countColor;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"countColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string countColor
    {
      get { return _countColor; }
      set { _countColor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}